### ISSUE TITLE
Can't craft metal tail

### ISSUE THREAD

**Issue by vNanonite** [FlansMods/FlansMod#945]
I'm trying to craft the metal tail but JEI tells me the recipe is 2x2 iron which is the exact recipe for an iron trapdoor.

**Comment by ChrisLane** [comment]
Was fixed in commit ef61514b5c112ece00862019080eadcef28e02a9 I believe. I'll release a pre-release on this repo this evening since official releases on the site seem a bit slow.

**Comment by ghost** [comment]
Still not craftable on 1.12.2-5.5.2

**Comment by ChrisLane** [comment]
> Still not craftable on 1.12.2-5.5.2

The fix was made after version 5.5.2. Please download the version [here](https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta) for the fix.

**Comment by Habbsy1** [comment]
hey , how do you get it to work once downloaded, i got the 5.6 build , but when loading in it says things are missing , do i need to download the source file? where do i put it?

**Comment by minecraftplayer12345** [comment]
Still doesn't work. I downloaded Modern Warfare and Simple Parts (The newer versions) And it didn't work.

**Comment by ChrisLane** [comment]
> Still doesn't work. I downloaded Modern Warfare and Simple Parts (The newer versions) And it didn't work.

The fix isn't related to the content packs, you need the newer version of the mod.
